# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - revive

  disable:
    - maligned  # deprecated
    - interfacer  # deprecated

  settings:
    gocyclo:
      min-complexity: 10
    misspell:
      locale: US
    lll:
      line-length: 120
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - mnd
          - funlen
          - gocyclo
          - dupl
          - lll
      - path: cmd/
        linters:
          - gochecknoinits

issues:
  max-issues-per-linter: 0
  max-same-issues: 0 